params:
  seed: 1764804769
  env:
    clip_observations: 5.0
    clip_actions: 1.0
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: false
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: true
    mlp:
      units:
      - 512
      - 512
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
    rnn:
      name: lstm
      units: 1024
      layers: 1
      before_mlp: true
      layer_norm: true
      concat_input: true
      concat_output: true
  load_checkpoint: false
  load_path: ''
  config:
    name: dextrah_lstm
    env_name: rlgpu
    device: cuda:0
    device_name: cuda:0
    multi_gpu: false
    ppo: true
    mixed_precision: false
    normalize_input: true
    normalize_value: true
    value_bootstrap: false
    num_actors: -1
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: true
    gamma: 0.998
    tau: 0.95
    learning_rate: 0.0001
    lr_schedule: linear
    schedule_type: standard
    kl_threshold: 0.013
    score_to_win: 100000
    max_epochs: 20000
    save_best_after: 100
    save_frequency: 200
    print_stats: true
    grad_norm: 1.0
    entropy_coef: 0.002
    truncate_grads: true
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 4096
    mini_epochs: 4
    critic_coef: 4
    clip_value: true
    seq_length: 16
    bound_loss_type: regularization
    bounds_loss_coef: 0.005
    zero_rnn_on_done: true
    central_value_config:
      minibatch_size: 4096
      mini_epochs: 4
      learning_rate: 5e-5
      kl_threshold: 0.016
      clip_value: true
      normalize_input: true
      truncate_grads: true
      network:
        name: actor_critic
        central_value: true
        mlp:
          units:
          - 1024
          - 512
          activation: elu
          d2rl: false
          initializer:
            name: default
          regularizer:
            name: None
        rnn:
          name: lstm
          units: 2048
          layers: 1
          before_mlp: false
          layer_norm: true
          concat_input: true
          concat_output: true
    player:
      deterministic: true
      games_num: 100000
      print_stats: true
    train_dir: /home/chizhang/projects/DEXTRAH/dextrah_lab/rl_games/logs/rl_games/dextrah_lstm
    full_experiment_name: 2025-12-04_00-32-49
wandb_activate: false
wandb_group: rl_gpu
wandb_name: large_scale_
wandb_entity: nvidia
wandb_project: dextrah-kuka-allegro
wandb_tags: []
hydra:
  output_subdir: null
  run:
    dir: .
