<?xml version="1.0"?>
<package format="2">
  <name>stereo_camera</name>
  <version>0.0.1</version>
  <description>Stereo camera utilities for TG2 Inspirehand.</description>
  <maintainer email="tg2@example.com">tg2</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
</package>
